
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeDetermineCompilerId.cmake:468 (find_file)"
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeDetermineCompilerId.cmake:506 (CMAKE_DETERMINE_COMPILER_ID_WRITE)"
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)"
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeDetermineCCompiler.cmake:122 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    mode: "file"
    variable: "src_in"
    description: "Path to a file."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "CMakeCCompilerId.c.in"
    candidate_directories:
      - "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/"
    found: "D:/Soft/Visual Studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.3/Modules/CMakeCCompilerId.c.in"
    search_context:
      ENV{PATH}:
        - "D:\\Soft\\Visual Studio\\VC\\Tools\\MSVC\\14.51.36231\\bin\\HostX64\\x64"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\VC\\VCPackages"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer"
        - "D:\\Soft\\Visual Studio\\MSBuild\\Current\\bin\\Roslyn"
        - "D:\\Soft\\Visual Studio\\Team Tools\\DiagnosticsHub\\Collector"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\Extensions\\Microsoft\\CodeCoverage.Console"
        - "D:\\Windows Kits\\10\\bin\\10.0.26100.0\\\\x64"
        - "D:\\Windows Kits\\10\\bin\\\\x64"
        - "D:\\Soft\\Visual Studio\\\\MSBuild\\Current\\Bin\\amd64"
        - "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\"
        - "D:\\Soft\\Visual Studio\\Common7\\Tools\\"
        - "D:\\Soft\\miniconda"
        - "D:\\Soft\\miniconda\\Library\\mingw-w64\\bin"
        - "D:\\Soft\\miniconda\\Library\\usr\\bin"
        - "D:\\Soft\\miniconda\\Library\\bin"
        - "D:\\Soft\\miniconda\\Scripts"
        - "D:\\Soft\\miniconda\\bin"
        - "D:\\Soft\\miniconda\\condabin"
        - "C:\\Users\\chyck\\.gemini\\antigravity\\bin"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "C:\\Program Files\\dotnet"
        - "D:\\Sumo\\SUMO\\bin"
        - "D:\\Sumo\\SUMO\\tools"
        - "C:\\Program Files\\Wolfram Research\\WolframScript"
        - "D:\\Soft\\Git\\cmd"
        - "D:\\Windows Kits\\10\\Windows Performance Toolkit"
        - "C:\\Program Files\\nodejs"
        - "C:\\Users\\chyck\\AppData\\Local\\agy\\bin"
        - "D:\\Soft\\miniconda"
        - "D:\\Soft\\miniconda\\Library\\mingw-w64\\bin"
        - "D:\\Soft\\miniconda\\Library\\usr\\bin"
        - "D:\\Soft\\miniconda\\Library\\bin"
        - "D:\\Soft\\miniconda\\Scripts"
        - "D:\\Sumo\\Python\\Scripts"
        - "D:\\Sumo\\Python"
        - "C:\\Users\\chyck\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\chyck\\.dotnet\\tools"
        - "D:\\Soft\\Microsoft VS Code\\bin"
        - "D:\\Soft\\MiKTex\\miktex\\bin\\x64"
        - "C:\\msys64\\ucrt64\\bin"
        - "C:\\Users\\chyck\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-7.0.2-full_build\\bin"
        - "C:\\Users\\chyck\\AppData\\Local\\Python\\bin"
        - "C:\\Users\\chyck\\AppData\\Roaming\\npm"
        - "C:\\Users\\chyck\\.local\\bin"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\PrivateAssemblies\\runtimes\\win-x64\\native"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja"
        - "D:\\Soft\\Visual Studio\\Common7\\IDE\\VC\\Linux\\bin\\ConnectionManagerExe"
        - "D:\\Soft\\Visual Studio\\VC\\vcpkg"
      ENV{INCLUDE}:
        - "D:\\Soft\\Visual Studio\\VC\\Tools\\MSVC\\14.51.36231\\include"
        - "D:\\Soft\\Visual Studio\\VC\\Tools\\MSVC\\14.51.36231\\ATLMFC\\include"
        - "D:\\Soft\\Visual Studio\\VC\\Auxiliary\\VS\\include"
        - "D:\\Windows Kits\\10\\include\\10.0.26100.0\\ucrt"
        - "D:\\Windows Kits\\10\\\\include\\10.0.26100.0\\\\um"
        - "D:\\Windows Kits\\10\\\\include\\10.0.26100.0\\\\shared"
        - "D:\\Windows Kits\\10\\\\include\\10.0.26100.0\\\\winrt"
        - "D:\\Windows Kits\\10\\\\include\\10.0.26100.0\\\\cppwinrt"
