[package]
name = "decfd"
version = "0.1.0"
description = "DeCFD on-chain program: jobs, tasks, stakes, audits, slashing, payouts"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "decfd"

[features]
default = []
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
